version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=sac_db
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: sac_db
    ports:
      - "3306:3306"
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
